version: "3.9"
services:
  php-apache:
    container_name: contapa2-m1-SG
    ports:
      - "8086:80"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
  php-apache2:
    container_name: contapa2-m1-SG-loadbalancing
    ports:
      - "8087:80"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
  nginx:
    build: './build/nginx'
    ports:
     - "8085:80"
    depends_on:
     - php-apache
     - php-apache2
  mysql:
    container_name: contsql-m1-SG
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "my-wonderful-website"
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData:
